# Installing the packages

In [1]:
!pip install pandas matplotlib seaborn -q

# Importing the Libraries

In [3]:
import numpy as np # for linear algebra
import pandas as pd # for Data processing 
import matplotlib.pyplot as plt # for data visualizations
import seaborn as sns # for statistical data visualization

print("Libraries loaded!")

Libraries loaded!

# Loading the Dataset

In [4]:
df = pd.read_csv('2019 dataset.csv')

# Exploratory Data Analysis

In [11]:
print("Shape:", "Columns:", df.shape[0], "Rows: ", df.shape[1])

Shape: Columns: 156 Rows:  9

In [12]:
#Displaying the first 10 rows of the dataset
df.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [20]:
# See all column names
print(df.columns.tolist())

['Overall rank', 'Country or region', 'Score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

In [21]:
#Understanding of data type helps for computation
df.dtypes

Overall rank                      int64
Country or region                object
Score                           float64
GDP per capita                  float64
Social support                  float64
Healthy life expectancy         float64
Freedom to make life choices    float64
Generosity                      float64
Perceptions of corruption       float64
dtype: object

In [22]:
#Print a concise summary of a DataFrame. 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     156 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB

In [32]:
#Checking for null/missing values

if df.isnull().sum().sum() == 0:
    print("No missing values found.")
else:
    for i in df:
        if df[i].isnull().sum() > 0:
            print(f'{i} has: {df[i].isnull().sum(), "missing values."}')

No missing values found.

In [34]:
# Check for duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [35]:
#Summary of the data set
df.describe()

,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,78.500000,5.407096,0.905147,1.208814,0.725244,0.392571,0.184846,0.110603
std,45.177428,1.113120,0.398389,0.299191,0.242124,0.143289,0.095254,0.094538
min,1.000000,2.853000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,39.750000,4.544500,0.602750,1.055750,0.547750,0.308000,0.108750,0.047000
50%,78.500000,5.379500,0.960000,1.271500,0.789000,0.417000,0.177500,0.085500
75%,117.250000,6.184500,1.232500,1.452500,0.881750,0.507250,0.248250,0.141250
max,156.000000,7.769000,1.684000,1.624000,1.141000,0.631000,0.566000,0.453000

### Top 10 happiest countries

In [39]:
print("Top 10 Happiest Countries:\n")
df['Country or region'].head(10)

Top 10 Happiest Countries:

0        Finland
1        Denmark
2         Norway
3        Iceland
4    Netherlands
5    Switzerland
6         Sweden
7    New Zealand
8         Canada
9        Austria
Name: Country or region, dtype: object

### Bottom 10 least happy

In [41]:
print("Bottom 10 Least Happiest Countries:\n")
df['Country or region'].tail(10)

Bottom 10 Least Happiest Countries:

146                       Haiti
147                    Botswana
148                       Syria
149                      Malawi
150                       Yemen
151                      Rwanda
152                    Tanzania
153                 Afghanistan
154    Central African Republic
155                 South Sudan
Name: Country or region, dtype: object